name: Ruby CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "2.6.10"
          - "3.2.2"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run rspec
        run: bundle exec rspec
      - name: Yaml structure checker
        run: >
          bundle exec ruby -e "require 'yaml_structure_checker';
          YamlStructureChecker::Runner.invoke(
          'spec/fixtures/checker/config/yaml_structure_checker_for_ci.yml')"
