name: Ruby CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "2.7.8"
          - "3.1.6"
          - "3.2.4"
          - "3.4.4"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run rspec
        run: bundle exec rspec
      - name: YAML structure checker
        run: >
          bundle exec ruby exe/yaml_structure_checker
          spec/fixtures/checker/config/yaml_structure_checker_for_ci.yml
